#include "sli.hxx"
// now it is using double
#define BYTESOFVAR_FLOAT 2
const unsigned int size_variable[] = { BYTESOFVAR_FLOAT, 
	BYTESOFVAR_FLOAT*3, BYTESOFVAR_FLOAT*3,
	BYTESOFVAR_FLOAT*3, BYTESOFVAR_FLOAT*3, BYTESOFVAR_FLOAT*16, 1};
#undef BYTESOFVAR_FLOAT

const char *str_registers[] = {
	"flg", "np", "le", ",p", "ls", "cs", "lstop", "codes", 
	"codee", "datas", "datae", "les", "__", "__", " __", "__",
};

const char *str_shadertype[] = {
	"surface",
	"light",
	"displacement",
	"volume",
	"imager"
};

const char *str_variabletype[] = {
	"float",
	"point",
	"vector",
	"normal",
	"color",
	"matrix",
	"string"
};


const char *str_cfuncs[] = {
	"radians_ff",
	"degrees_ff",
	"sin_ff",
	"asin_ff",
	"cos_ff",
	"acos_ff",
	"tan_ff",
	"atan_ff",
	"atan_fff",
	"pow_fff",

	"exp_ff",
	"sqrt_ff",
	"inversesqrt_ff",
	"log_ff",
	"log_fff",
	"mod_fff",
	"abs_ff",
	"sign_ff",
	"min_fff",
	"min_ppp",

	"min_vvv",
	"min_nnn",
	"min_ccc",
	"max_fff",
	"max_ppp",
	"max_vvv",
	"max_nnn",
	"max_ccc",
	"clamp_ffff",
	"clamp_pppp",

	"clamp_vvvv",
	"clamp_nnnn",
	"clamp_cccc",
	"mix_ffff",
	"mix_pppf",
	"mix_vvvf",
	"mix_nnnf",
	"mix_cccf",
	"floor_ff",
	"ceil_ff",

	"round_ff",
	"step_fff",
	"smoothstep_ffff",
	"filterstep_fff",
	"filterstep_ffff",
	"spline_fff",
	"spline_fsff",
	"spline_ffF",
	"spline_fsfF",
	"spline_cfc",

	"spline_csfc",
	"spline_cfC",
	"spline_csfC",
	"spline_pfp",
	"spline_psfp",
	"spline_pfP",
	"spline_psfP",
	"spline_vfv",
	"spline_vsfv",
	"spline_vfV",

	"spline_vsfV",
	"Du_ff",
	"Dv_ff",
	"Deriv_fff",
	"Du_cc",
	"Dv_cc",
	"Deriv_ccf",
	"Du_vp",
	"Dv_vp",
	"Deriv_vpf",

	"Du_vv",
	"Dv_vv",
	"Deriv_vvf",
	"random_f_",
	"random_c_",
	"random_p_",
	"noise_ff",
	"noise_fff",
	"noise_fp",
	"noise_fpf",

	"noise_cf",
	"noise_cff",
	"noise_cp",
	"noise_cpf",
	"noise_pf",
	"noise_pff",
	"noise_pp",
	"noise_ppf",
	"noise_vf",
	"noise_vff",

	"noise_vp",
	"noise_vpf",
	"pnoise_fff",
	"pnoise_fffff",
	"pnoise_fpp",
	"pnoise_fpfpf",
	"pnoise_cff",
	"pnoise_cffff",
	"pnoise_cpp",
	"pnoise_cpfpf",

	"pnoise_pff",
	"pnoise_pffff",
	"pnoise_ppp",
	"pnoise_ppfpf",
	"pnoise_vff",
	"pnoise_vffff",
	"pnoise_vpp",
	"pnoise_vpfpf",
	"cellnoise_ff",
	"cellnoise_fff",

	"cellnoise_fp",
	"cellnoise_fpf",
	"cellnoise_cf",
	"cellnoise_cff",
	"cellnoise_cp",
	"cellnoise_cpf",
	"cellnoise_pf",
	"cellnoise_pff",
	"cellnoise_pp",
	"cellnoise_ppf",

	"cellnoise_vf",
	"cellnoise_vff",
	"cellnoise_vp",
	"cellnoise_vpf",
	"xcomp_fp",
	"ycomp_fp",
	"zcomp_fp",
	"xcomp_fv",
	"ycomp_fv",
	"zcomp_fv",

	"xcomp_fn",
	"ycomp_fn",
	"zcomp_fn",
	"setxcomp__pf",
	"setycomp__pf",
	"setzcomp__pf",
	"setxcomp__vf",
	"setycomp__vf",
	"setzcomp__vf",
	"setxcomp__nf",

	"setycomp__nf",
	"setzcomp__nf",
	"length_fv",
	"normalize_vv",
	"distance_fpp",
	"ptlined_fppp",
	"rotate_fpfpp",
	"area_fp",
	"faceforward_vvv",
	"faceforward_vvvv",

	"reflect_vvv",
	"refract_vvvf",
	"fresnel__vvfff",
	"fresnel__vvfffvv",
	"transform_psp",
	"transform_pssp",
	"transform_pmp",
	"transform_psmp",
	"vtransform_vsv",
	"vtransform_vssv",

	"vtransform_vmv",
	"vtransform_vsmv",
	"ntransform_nsn",
	"ntransform_nssn",
	"ntransform_nmn",
	"ntransform_nsmn",
	"depth_fp",
	"calculatenormal_vp",
	"comp_fcf",
	"setcomp_cff",

	"mix_cccf",
	"ctransform_csc",
	"ctransform_cssc",
	"comp_fmff",
	"setcomp__mfff",
	"determinant_fm",
	"translate_mmt",
	"rotate_mmfv",
	"scale_mmp",
	"concat_sss",

	"printf__s",
	"format_ss",
	"match_fss",
	"ambient_c_",
	"diffuse_cv",
	"specular_cvvf",
	"specularbrdf_cvvvf",
	"phong_cvvf",
	"trace_cpp",
	"texture_fs",

	"texture_fsff",
	"texture_cs",
	"texture_csff",
	"texture_fsf",
	"texture_fsfff",
	"texture_csf",
	"texture_csfff",
	"environment_fsff",
	"environment_csff",
	"environment_fsfff",

	"environment_csfff",
	"shadow_fsff",
	"shadow_fsfff",
	"textureinfo_fs",
	"solar__",
	"solar__vf",
	"illuminate__p",
	"illuminate__pvf",
	"illuminance_p",
	"illuminance_sp",
	"illuminance_pvf",

	"illuminance_spvf",
	"null"
};

const EnvDesc desc_surfaceenv[24] = {
	{ "Cs", VAR_COLOR | VAR_VARYING },
	{ "Os", VAR_COLOR | VAR_VARYING },
	{ "P", VAR_POINT | VAR_VARYING },
	{ "dPdu", VAR_VECTOR | VAR_VARYING },
	{ "dPdv", VAR_VECTOR | VAR_VARYING },
	{ "N", VAR_NORMAL | VAR_VARYING },
	{ "Ng", VAR_VECTOR | VAR_VARYING },
	{ "u", VAR_FLOAT | VAR_VARYING },
	{ "v", VAR_FLOAT | VAR_VARYING },
	{ "du", VAR_FLOAT | VAR_VARYING },
	{ "dv", VAR_FLOAT | VAR_VARYING },
	{ "s", VAR_FLOAT | VAR_VARYING },
	{ "t", VAR_FLOAT | VAR_VARYING },
	{ "L", VAR_VECTOR | VAR_VARYING },
	{ "Cl", VAR_COLOR | VAR_VARYING },
	{ "Ol", VAR_COLOR | VAR_VARYING },
	{ "E", VAR_POINT | VAR_UNIFORM },
	{ "I", VAR_VECTOR | VAR_VARYING },
	{ "ncomps", VAR_FLOAT | VAR_UNIFORM },
	{ "time", VAR_FLOAT | VAR_UNIFORM },
	{ "dtime", VAR_FLOAT | VAR_UNIFORM },
	{ "dPdtime", VAR_VECTOR | VAR_VARYING },
	{ "Ci", VAR_COLOR | VAR_VARYING | VAR_OUTPUT },
	{ "Oi", VAR_COLOR | VAR_VARYING | VAR_OUTPUT }
};

const EnvDesc desc_lightenv[19] = {
	{ "P", VAR_POINT | VAR_VARYING },
	{ "dPdu", VAR_VECTOR | VAR_VARYING },
	{ "dPdv", VAR_VECTOR | VAR_VARYING },
	{ "N", VAR_NORMAL | VAR_VARYING },
	{ "Ng", VAR_NORMAL | VAR_VARYING },
	{ "u", VAR_FLOAT | VAR_VARYING },
	{ "v", VAR_FLOAT | VAR_VARYING },
	{ "du", VAR_FLOAT | VAR_VARYING },
	{ "dv", VAR_FLOAT | VAR_VARYING },
	{ "s", VAR_FLOAT | VAR_VARYING },
	{ "t", VAR_FLOAT | VAR_VARYING },
	{ "L", VAR_VECTOR | VAR_VARYING },
	{ "Ps", VAR_POINT | VAR_VARYING },
	{ "E", VAR_POINT | VAR_UNIFORM },
	{ "ncomps", VAR_FLOAT | VAR_UNIFORM },
	{ "time", VAR_FLOAT | VAR_UNIFORM },
	{ "dtime", VAR_FLOAT | VAR_UNIFORM },
	{ "Cl", VAR_COLOR | VAR_VARYING | VAR_OUTPUT },
	{ "Ol", VAR_COLOR | VAR_VARYING | VAR_OUTPUT }
};

const EnvDesc desc_volumeenv[10] = {
	{ "P", VAR_POINT | VAR_VARYING },
	{ "I", VAR_VECTOR | VAR_VARYING },
	{ "E", VAR_POINT | VAR_UNIFORM },
	{ "Cl", VAR_COLOR | VAR_VARYING },
	{ "Ol", VAR_COLOR | VAR_VARYING },
	{ "ncomps", VAR_FLOAT | VAR_UNIFORM },
	{ "time", VAR_FLOAT | VAR_UNIFORM },
	{ "dtime", VAR_FLOAT | VAR_UNIFORM },
	{ "Ci", VAR_COLOR | VAR_VARYING | VAR_OUTPUT },
	{ "Oi", VAR_COLOR | VAR_VARYING | VAR_OUTPUT }
};

const EnvDesc desc_displacementenv[17] = {
	{ "P", VAR_POINT | VAR_VARYING | VAR_OUTPUT },
	{ "dPdu", VAR_VECTOR | VAR_VARYING },
	{ "dPdv", VAR_VECTOR | VAR_VARYING },
	{ "N", VAR_NORMAL | VAR_VARYING | VAR_OUTPUT},
	{ "Ng", VAR_NORMAL | VAR_VARYING },
	{ "I", VAR_VECTOR | VAR_VARYING },
	{ "E", VAR_POINT | VAR_UNIFORM },
	{ "u", VAR_FLOAT | VAR_VARYING },
	{ "v", VAR_FLOAT | VAR_VARYING },
	{ "du", VAR_FLOAT | VAR_VARYING },
	{ "dv", VAR_FLOAT | VAR_VARYING },
	{ "s", VAR_FLOAT | VAR_VARYING },
	{ "t", VAR_FLOAT | VAR_VARYING },
	{ "ncomps", VAR_FLOAT | VAR_UNIFORM },
	{ "time", VAR_FLOAT | VAR_UNIFORM },
	{ "dtime", VAR_FLOAT | VAR_UNIFORM },
	{ "dPdtime", VAR_VECTOR | VAR_VARYING },
};

const EnvDesc desc_imagerenv[7] = {
	{ "P", VAR_POINT | VAR_VARYING },
	{ "Ci", VAR_COLOR | VAR_VARYING | VAR_OUTPUT },
	{ "Oi", VAR_COLOR | VAR_VARYING | VAR_OUTPUT },
	{ "alpha", VAR_FLOAT | VAR_UNIFORM },
	{ "ncomps", VAR_FLOAT | VAR_UNIFORM },
	{ "time", VAR_FLOAT | VAR_UNIFORM },
	{ "dtime", VAR_FLOAT | VAR_UNIFORM }
};

